#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
    # datasource PostgreSQL
server:
  port: 8081
spring:
  application:
    name: Pos-ProjetoAplicado
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pos_xpe_pa
    username: pa
    password: Uw3j8ev_cAk5RALiFum1

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    generic-properties:
      properties:
        historyTimeToLive: 8
      enableScriptEngineCaching: true
      enableScriptEngineLoadExternalResources: true

  client:
    mode: self-managed
    zeebe:
      enabled: false
      grpc-address: http://127.0.0.1:26500
      rest-address: http://127.0.0.1:8082